pub mod config;
pub mod error;
pub mod domain;
pub mod context;
pub mod application;
pub mod adapter;
pub mod infrastructure;
pub mod api;
pub mod auth;
pub mod protocol;
pub mod transport;
pub mod monitoring;
pub mod sql_mappers;

pub use config::AppConfig;
pub use context::ServiceRegistry;
pub use infrastructure::DbRepository;
pub use infrastructure::EventBus;
pub use infrastructure::cluster::ClusterManager;
pub use application::{DeviceService, StreamService, SessionService, MediaServerService};
pub use auth::{AuthState, CasbinManager, JwtConfig};
pub use auth::auth_db::PostgresAuthRepository;
pub use protocol::{AdapterRegistry, ProtocolMatcher, ProtocolType};
pub use protocol::gb28181::Gb28181Adapter;
pub use protocol::onvif::OnvifAdapter;
pub use protocol::websocket::WebSocketAdapter;
pub use transport::{TcpServer, UdpServer, ServerConfig, UdpServerConfig};
pub use monitoring::Metrics;